App strings reworked
Fox2Code/FoxMagiskModuleManager pull request #134
Opened 2022-04-17 04:35 UTC by comradekingu

Some suggestions for improvements, the "DNS over HTTPS" is the one I noticed the most.
Don't agree to the CoC.

2022-04-17 04:36 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="use_magisk_install_command_pref">Use magisk module install command</string>
```suggestion
    <string name="use_magisk_install_command_pref">Use \"magisk module install\" command</string>
```
?

2022-04-17 14:15 UTC, Fox2Code requested changes

2022-04-17 14:18 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="file_picker_wierd">Your file picker returned a non standard response.</string>
```suggestion
    <string name="file_picker_wierd">Your file picker returned a non-standard response.</string>
```

2022-04-17 14:19 UTC, Fox2Code commented
Everything else seems fine to me.
I feel weird for the "from carrying out actions" in lockdown mode description, but since I can't figure out why I think it's maybe just a personal preferences.

2022-04-17 14:22 UTC, comradekingu commented
@Fox2Code 
Happy to change it back if you find something you like more.
Hopefully it all can be put on a Weblate instance now that it is more polished.
Not so easy to keep that updated between files otherwise.

2022-04-17 14:37 UTC, Fox2Code commented
I'll merge this at the same time as #107 for `0.5.0`. 
Someone reported an optimization bug on telegram 10 minutes after I released `0.4.4`...
So I may do a `0.4.5`, or I may jump to `0.5.0` directly, depend on many things.

2022-04-19 01:35 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="app_update">Update</string>
```suggestion
    <string name="app_update">Upgrade</string>
```

2022-04-19 01:35 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="require_android_6">Require Android 6.0+</string>
```suggestion
    <string name="require_android_6">Requires Android 6.0+</string>
```
?

2022-04-19 01:36 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="magisk_outdated">Magisk is outdated!</string>
```suggestion
    <string name="magisk_outdated">There is a new version of Magisk to install!</string>
```

2022-04-19 01:38 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="invalid_format">The selected module is in an invalid format</string>
```suggestion
    <string name="invalid_format">The selected module has an invalid format</string>
```
This is minute, but I think if it is the file extention "has" is better, and
if the internal anything is the problem then "is in" is better.

2022-04-19 01:39 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="force_dark_terminal_title">Force dark-mode terminal</string>
```suggestion
    <string name="force_dark_terminal_title">Dark terminal</string>
```
?

2022-04-19 01:40 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="force_english_pref">Force English language</string>
```suggestion
    <string name="force_english_pref">English app language</string>
```

2022-04-19 01:41 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="file_picker_failure">Your current file picker failed to grant access to the file.</string>
```suggestion
    <string name="file_picker_failure">Your current file picker could not access the file.</string>
```
Same same? Is there a reason why it isn't a file browser?

2022-04-19 01:43 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +    <string name="disable_low_quality_module_filter_pref">Turn off low quality module filter</string>
```suggestion
    <string name="disable_low_quality_module_filter_pref">Show low quality modules</string>
```
?

2022-04-19 01:44 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +        and/or indicating poor module quality. Turn this off at your own risk!
```suggestion
        and/or indicating poor module quality.\nTurn this off at your own risk!
```
?

2022-04-19 01:45 UTC, comradekingu commented on app/src/main/res/values/strings.xml
> +        terminal extensions. Useful if a module misuses Fox\'s Mmm extensions.
```suggestion
        terminal extensions.\nUseful if a module misuses Fox\'s Mmm extensions.
```
?

2022-04-19 01:45 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>      <string name="wrap_text_pref">Wrap text</string>
```suggestion
    <string name="wrap_text_pref">Text wrapping</string>
```
Slightly better?

2022-04-19 01:46 UTC, comradekingu commented on app/src/main/res/values/strings.xml
>          Wrap text to a new line instead of putting
```suggestion
        Show text on multiple lines instead of putting
```

2022-04-19 01:48 UTC, comradekingu commented
@Fox2Code After making the nb_NO translations I found some improvements, tried to avoid inconsistencies, and added whatever small improvements I could find.
If you find the time, maybe you can have a look. Nothing showstopping.

2022-04-26 13:58 UTC, Fox2Code commented
Yeah everything you did seems fine.
Also for context `disable_low_quality_module_filter_pref` is disabled in release builds.
Also you not agreeing to CoC doesn't means it doesn't apply here, see #135
I am the only one that need to agree to it as I'm the one handling bans, but I am not strict in enforcing it.

2022-05-03 15:12 UTC, Fox2Code commented
I have reworked code of conduct, you can tell me what you think.
Also you didn't expressed if you wanted or not to be credited or not.
I will assume you don't want to receive credits again, but I would still like you to confirm that if possible.

2022-05-03 15:12 UTC, merged